seed: 42

data:
  root: ../archive/data
  image_size: [128, 128]
  validation_split: 0.2
  test_split: 0.2
  batch_size: 32

training:
  epochs: 30
  learning_rate: 0.001
  dense_units: 128
  dropout_rate: 0.5
  early_stopping_patience: 5
  reduce_lr_patience: 3
  reduce_lr_factor: 0.5
  min_lr: 1.0e-7

artifacts:
  root: ../artifacts
  model_registry: ../models

visualization:
  enabled: true
  dpi: 300
  style: darkgrid
  color_palette: Set2
  sample_predictions_count: 16
  include_roc_curve: true
  include_pr_curve: true
  include_lr_schedule: true
  include_class_distribution: true
  include_dashboard: true
